export const careers = [
  {
    name: "Software Engineer",
    description: "Thiết kế và phát triển các ứng dụng và hệ thống phần mềm.",
    average_salary: 35_000_000,
    growth_rate: 0.22,
    topic_id: null,
    related_topics: null,
    skills: ["JavaScript", "Node.js", "React", "Git"],
  },
  {
    name: "Data Scientist",
    description:
      "Phân tích và giải thích dữ liệu phức tạp để giúp các công ty đưa ra quyết định.",
    average_salary: 40_000_000,
    growth_rate: 0.31,
    topic_id: null,
    related_topics: null,
    skills: ["Python", "Pandas", "Học máy", "SQL"],
  },
  {
    name: "UI/UX Designer",
    description: "Tạo ra giao diện người dùng thân thiện và dễ sử dụng.",
    average_salary: 25_000_000,
    growth_rate: 0.18,
    topic_id: null,
    related_topics: null,
    skills: ["Figma", "Adobe XD", "Nghiên cứu người dùng", "Prototyping"],
  },
  {
    name: "DevOps Engineer",
    description:
      "Thiết kế, triển khai và quản lý các hệ thống tự động hóa và cơ sở hạ tầng cho phát triển và vận hành phần mềm.",
    average_salary: 45_000_000,
    growth_rate: 0.24,
    topic_id: null,
    related_topics: null,
    skills: ["Docker", "Kubernetes", "AWS", "CI/CD", "Terraform", "Jenkins"],
  },
  {
    name: "Data Engineer",
    description:
      "Thiết kế, xây dựng và duy trì các hệ thống xử lý dữ liệu quy mô lớn, đảm bảo dữ liệu được thu thập, lưu trữ và phân tích hiệu quả.",
    average_salary: 38_000_000,
    growth_rate: 0.27,
    topic_id: null,
    related_topics: null,
    skills: ["Python", "SQL", "Spark", "Hadoop", "ETL", "Data Warehousing"],
  },
  {
    name: "Cybersecurity Analyst",
    description: "Bảo vệ các hệ thống và mạng khỏi các mối đe dọa mạng.",
    average_salary: 42_000_000,
    growth_rate: 0.28,
    topic_id: null,
    related_topics: null,
    skills: ["Bảo mật mạng", "Tường lửa", "SIEM", "Hack đạo đức"],
  },
  {
    name: "Product Manager",
    description: "Giám sát sự phát triển và triển khai các sản phẩm.",
    average_salary: 50_000_000,
    growth_rate: 0.19,
    topic_id: null,
    related_topics: null,
    skills: [
      "Agile",
      "Chiến lược sản phẩm",
      "Nghiên cứu thị trường",
      "Lập kế hoạch sản phẩm",
    ],
  },
  {
    name: "Business Analyst",
    description:
      "Đánh giá các quy trình kinh doanh và đưa ra các khuyến nghị dựa trên dữ liệu.",
    average_salary: 28_000_000,
    growth_rate: 0.14,
    topic_id: null,
    related_topics: null,
    skills: [
      "SQL",
      "Excel",
      "Trực quan hóa dữ liệu",
      "Giao tiếp với các bên liên quan",
    ],
  },
  {
    name: "Cloud Engineer",
    description: "Triển khai và quản lý cơ sở hạ tầng và dịch vụ đám mây.",
    average_salary: 45_000_000,
    growth_rate: 0.26,
    topic_id: null,
    related_topics: null,
    skills: ["AWS", "Azure", "Terraform", "Bảo mật đám mây"],
  },
  {
    name: "AI Engineer",
    description: "Phát triển các mô hình và hệ thống trí tuệ nhân tạo.",
    average_salary: 55_000_000,
    growth_rate: 0.35,
    topic_id: null,
    related_topics: null,
    skills: ["Python", "TensorFlow", "PyTorch", "Học sâu"],
  },
  {
    name: "Frontend Developer",
    description:
      "Phát triển giao diện người dùng và trải nghiệm người dùng cho các ứng dụng web.",
    average_salary: 32_000_000,
    growth_rate: 0.25,
    topic_id: null,
    related_topics: null,
    skills: ["React", "Vue.js", "TypeScript", "CSS"],
  },
  {
    name: "Mobile App Developer",
    description:
      "Tạo ra các ứng dụng cho các nền tảng di động như Android và iOS.",
    average_salary: 35_000_000,
    growth_rate: 0.2,
    topic_id: null,
    related_topics: null,
    skills: ["Flutter", "React Native", "Swift", "Kotlin"],
  },
  {
    name: "QA Engineer",
    description:
      "Đảm bảo chất lượng phần mềm thông qua kiểm thử và tự động hóa.",
    average_salary: 25_000_000,
    growth_rate: 0.17,
    topic_id: null,
    related_topics: null,
    skills: ["Selenium", "Bài kiểm thử", "Jest", "Tự động hóa"],
  },
  {
    name: "Blockchain Developer",
    description: "Xây dựng và duy trì các ứng dụng dựa trên blockchain.",
    average_salary: 60_000_000,
    growth_rate: 0.33,
    topic_id: null,
    related_topics: null,
    skills: ["Solidity", "Ethereum", "Smart Contracts", "Web3.js"],
  },
  {
    name: "IT Support Specialist",
    description:
      "Cung cấp hỗ trợ kỹ thuật cho các vấn đề phần mềm và phần cứng.",
    average_salary: 15_000_000,
    growth_rate: 0.12,
    topic_id: null,
    related_topics: null,
    skills: ["Helpdesk", "Khắc phục sự cố", "Hỗ trợ khách hàng", "Mạng"],
  },
  {
    name: "Game Developer",
    description: "Tạo ra các trò chơi tương tác cho các nền tảng khác nhau.",
    average_salary: 30_000_000,
    growth_rate: 0.16,
    topic_id: null,
    related_topics: null,
    skills: ["Unity", "Unreal Engine", "C#", "Mô hình 3D"],
  },
  {
    name: "Technical Writer",
    description: "Tạo ra tài liệu kỹ thuật và hướng dẫn sử dụng.",
    average_salary: 20_000_000,
    growth_rate: 0.1,
    topic_id: null,
    related_topics: null,
    skills: ["Markdown", "Tài liệu API", "Viết", "Chú ý đến chi tiết"],
  },
  {
    name: "Network Administrator",
    description: "Duy trì và xử lý sự cố hạ tầng mạng.",
    average_salary: 25_000_000,
    growth_rate: 0.13,
    topic_id: null,
    related_topics: null,
    skills: ["Mạng", "Tường lửa", "VPN", "Cisco"],
  },
  {
    name: "Digital Marketer",
    description: "Phát triển và thực hiện các chiến lược marketing trực tuyến.",
    average_salary: 22_000_000,
    growth_rate: 0.23,
    topic_id: null,
    related_topics: null,
    skills: ["SEO", "Google Analytics", "Mạng xã hội", "Tiếp thị qua email"],
  },
  {
    name: "Robotics Engineer",
    description:
      "Thiết kế robot và các hệ thống tự động hóa cho ngành công nghiệp.",
    average_salary: 40_000_000,
    growth_rate: 0.27,
    topic_id: null,
    related_topics: null,
    skills: ["C++", "ROS", "Cảm biến", "Hệ thống điều khiển"],
  },
  {
    name: "Backend Developer",
    description:
      "Phát triển và duy trì phần server-side của ứng dụng web và mobile.",
    average_salary: 35_000_000,
    growth_rate: 0.21,
    topic_id: null,
    related_topics: null,
    skills: ["Java", "Spring Boot", "Node.js", "SQL"],
  },
  {
    name: "Full Stack Developer",
    description: "Làm việc cả frontend và backend của các ứng dụng web.",
    average_salary: 40_000_000,
    growth_rate: 0.25,
    topic_id: null,
    related_topics: null,
    skills: ["JavaScript", "Node.js", "React", "MongoDB"],
  },
  {
    name: "Computer Vision Engineer",
    description: "Xây dựng các hệ thống xử lý và giải thích dữ liệu hình ảnh.",
    average_salary: 45_000_000,
    growth_rate: 0.3,
    topic_id: null,
    related_topics: null,
    skills: ["OpenCV", "Python", "Xử lý ảnh", "Học máy"],
  },
  {
    name: "Database Administrator",
    description:
      "Quản lý và duy trì các hệ thống cơ sở dữ liệu và đảm bảo tính toàn vẹn của dữ liệu.",
    average_salary: 30_000_000,
    growth_rate: 0.2,
    topic_id: null,
    related_topics: null,
    skills: ["SQL", "MySQL", "PostgreSQL", "Oracle"],
  },
  {
    name: "System Architect",
    description:
      "Thiết kế và quản lý các hệ thống và cơ sở hạ tầng CNTT phức tạp.",
    average_salary: 50_000_000,
    growth_rate: 0.15,
    topic_id: null,
    related_topics: null,
    skills: ["Thiết kế hệ thống", "Điện toán đám mây", "Mạng", "Tự động hóa"],
  },
  {
    name: "SEO Specialist",
    description:
      "Tối ưu hóa website để cải thiện thứ hạng trên công cụ tìm kiếm.",
    average_salary: 25_000_000,
    growth_rate: 0.18,
    topic_id: null,
    related_topics: null,
    skills: ["SEO", "Google Analytics", "Content Strategy", "Keyword Research"],
  },
  {
    name: "Network Engineer",
    description: "Thiết kế và quản lý các mạng máy tính.",
    average_salary: 28_000_000,
    growth_rate: 0.17,
    topic_id: null,
    related_topics: null,
    skills: ["TCP/IP", "Routing", "Switching", "Cisco"],
  },
  {
    name: "Cloud Solutions Architect",
    description:
      "Thiết kế các giải pháp đám mây và đảm bảo hiệu quả hạ tầng đám mây.",
    average_salary: 55_000_000,
    growth_rate: 0.28,
    topic_id: null,
    related_topics: null,
    skills: ["AWS", "Azure", "GCP", "Cloud Security"],
  },
  {
    name: "Artificial Intelligence Researcher",
    description:
      "Tiến hành nghiên cứu để phát triển lĩnh vực trí tuệ nhân tạo.",
    average_salary: 60_000_000,
    growth_rate: 0.33,
    topic_id: null,
    related_topics: null,
    skills: ["Machine Learning", "Deep Learning", "Neural Networks", "Python"],
  },
  {
    name: "Content Strategist",
    description:
      "Phát triển chiến lược nội dung để nâng cao khả năng nhận diện thương hiệu.",
    average_salary: 22_000_000,
    growth_rate: 0.19,
    topic_id: null,
    related_topics: null,
    skills: ["Content Strategy", "SEO", "Writing", "Social Media"],
  },
  {
    name: "Marketing Manager",
    description:
      "Lãnh đạo các chiến dịch và chiến lược marketing để thúc đẩy sự phát triển kinh doanh.",
    average_salary: 35_000_000,
    growth_rate: 0.15,
    topic_id: null,
    related_topics: null,
    skills: [
      "Market Research",
      "Advertising",
      "Campaign Management",
      "Analytics",
    ],
  },
  {
    name: "Legal Counsel",
    description: "Cung cấp lời khuyên pháp lý và hướng dẫn cho các tổ chức.",
    average_salary: 45_000_000,
    growth_rate: 0.05,
    topic_id: null,
    related_topics: null,
    skills: ["Contract Law", "Legal Research", "Compliance", "Negotiation"],
  },
  {
    name: "Human Resources Manager",
    description: "Quản lý tuyển dụng, quan hệ nhân viên và phát triển tổ chức.",
    average_salary: 30_000_000,
    growth_rate: 0.1,
    topic_id: null,
    related_topics: null,
    skills: [
      "Recruitment",
      "Employee Relations",
      "Performance Management",
      "HR Strategy",
    ],
  },
  {
    name: "Financial Analyst",
    description:
      "Phân tích dữ liệu tài chính và cung cấp những thông tin kinh doanh cho quá trình ra quyết định.",
    average_salary: 28_000_000,
    growth_rate: 0.12,
    topic_id: null,
    related_topics: null,
    skills: [
      "Financial Modeling",
      "Excel",
      "Financial Analysis",
      "Investment Strategy",
    ],
  },
  {
    name: "Operations Manager",
    description:
      "Giám sát sản xuất, logistics và các hoạt động hàng ngày của doanh nghiệp.",
    average_salary: 32_000_000,
    growth_rate: 0.08,
    topic_id: null,
    related_topics: null,
    skills: [
      "Project Management",
      "Logistics",
      "Supply Chain",
      "Operations Strategy",
    ],
  },
  {
    name: "Agricultural Engineer",
    description:
      "Thiết kế các hệ thống và cấu trúc cho nông nghiệp và sản xuất nông sản.",
    average_salary: 25_000_000,
    growth_rate: 0.12,
    topic_id: null,
    related_topics: null,
    skills: [
      "Agricultural Systems",
      "Sustainability",
      "Engineering Design",
      "Soil Science",
    ],
  },
  {
    name: "Marine Biologist",
    description:
      "Nghiên cứu các sinh vật biển và hệ sinh thái để hiểu về hành vi và môi trường của chúng.",
    average_salary: 20_000_000,
    growth_rate: 0.05,
    topic_id: null,
    related_topics: null,
    skills: ["Marine Ecology", "Field Research", "Oceanography", "Biology"],
  },
  {
    name: "Meteorologist",
    description:
      "Nghiên cứu các mô hình thời tiết và hiện tượng khí quyển để dự báo thời tiết và tư vấn các vấn đề liên quan đến khí hậu.",
    average_salary: 22_000_000,
    growth_rate: 0.08,
    topic_id: null,
    related_topics: null,
    skills: [
      "Climate Modeling",
      "Data Analysis",
      "Meteorological Equipment",
      "Statistics",
    ],
  },
  {
    name: "Biomedical Engineer",
    description:
      "Thiết kế và phát triển các thiết bị y tế, trang thiết bị và công nghệ để cải thiện chăm sóc sức khỏe.",
    average_salary: 35_000_000,
    growth_rate: 0.1,
    topic_id: null,
    related_topics: null,
    skills: ["Biomedical Devices", "Medical Imaging", "Bioinformatics", "CAD"],
  },
  {
    name: "Chartered Accountant",
    description:
      "Chuẩn bị các hồ sơ tài chính, kiểm toán tài khoản và cung cấp lời khuyên tài chính.",
    average_salary: 35_000_000,
    growth_rate: 0.04,
    topic_id: null,
    related_topics: null,
    skills: ["Accounting", "Taxation", "Audit", "Financial Reporting"],
  },
  {
    name: "Clinical Psychologist",
    description:
      "Chẩn đoán và điều trị các vấn đề sức khỏe tâm lý thông qua liệu pháp và các kỹ thuật hành vi.",
    average_salary: 30_000_000,
    growth_rate: 0.07,
    topic_id: null,
    related_topics: null,
    skills: [
      "Therapy",
      "Cognitive Behavioral Therapy",
      "Psychological Assessment",
      "Mental Health",
    ],
  },
  {
    name: "Social Worker",
    description:
      "Hỗ trợ cá nhân và cộng đồng vượt qua các thử thách cá nhân, thường liên quan đến nghèo đói, lạm dụng hoặc sức khỏe tâm thần.",
    average_salary: 15_000_000,
    growth_rate: 0.06,
    topic_id: null,
    related_topics: null,
    skills: ["Counseling", "Social Services", "Crisis Management", "Advocacy"],
  },
  {
    name: "Event Planner",
    description:
      "Lên kế hoạch và điều phối các sự kiện như đám cưới, hội nghị và các cuộc họp doanh nghiệp.",
    average_salary: 20_000_000,
    growth_rate: 0.09,
    topic_id: null,
    related_topics: null,
    skills: [
      "Event Coordination",
      "Vendor Management",
      "Project Management",
      "Communication",
    ],
  },
  {
    name: "Real Estate Agent",
    description: "Hỗ trợ khách hàng mua, bán hoặc cho thuê bất động sản.",
    average_salary: 25_000_000,
    growth_rate: 0.08,
    topic_id: null,
    related_topics: null,
    skills: ["Negotiation", "Real Estate Law", "Property Management", "Sales"],
  },
  {
    name: "Chiropractor",
    description:
      "Chẩn đoán và điều trị các vấn đề về cơ xương khớp, tập trung vào cột sống và hệ thần kinh.",
    average_salary: 30_000_000,
    growth_rate: 0.04,
    topic_id: null,
    related_topics: null,
    skills: [
      "Chiropractic Care",
      "Musculoskeletal Assessment",
      "Patient Care",
      "Spinal Manipulation",
    ],
  },
  {
    name: "Film Director",
    description:
      "Giám sát các khía cạnh sáng tạo và kỹ thuật trong sản xuất phim.",
    average_salary: 40_000_000,
    growth_rate: 0.06,
    topic_id: null,
    related_topics: null,
    skills: ["Film Production", "Directing", "Scriptwriting", "Cinematography"],
  },
  {
    name: "Veterinarian",
    description: "Cung cấp chăm sóc y tế và điều trị cho động vật.",
    average_salary: 25_000_000,
    growth_rate: 0.05,
    topic_id: null,
    related_topics: null,
    skills: ["Animal Care", "Surgery", "Veterinary Medicine", "Diagnostics"],
  },
  {
    name: "Dietitian",
    description:
      "Tư vấn cho cá nhân về dinh dưỡng và chế độ ăn uống để cải thiện sức khỏe và quản lý bệnh tật.",
    average_salary: 20_000_000,
    growth_rate: 0.07,
    topic_id: null,
    related_topics: null,
    skills: [
      "Nutrition",
      "Health Education",
      "Diet Plans",
      "Medical Nutrition Therapy",
    ],
  },
  {
    name: "Art Curator",
    description:
      "Quản lý và giám sát việc thu thập, bảo tồn và trưng bày các bộ sưu tập nghệ thuật.",
    average_salary: 18_000_000,
    growth_rate: 0.03,
    topic_id: null,
    related_topics: null,
    skills: [
      "Art History",
      "Museum Management",
      "Exhibit Planning",
      "Curation",
    ],
  },
  {
    name: "Speech-Language Pathologist",
    description: "Chẩn đoán và điều trị các rối loạn giao tiếp và nuốt.",
    average_salary: 22_000_000,
    growth_rate: 0.08,
    topic_id: null,
    related_topics: null,
    skills: [
      "Speech Therapy",
      "Language Development",
      "Swallowing Therapy",
      "Patient Care",
    ],
  },
  {
    name: "Astronomer",
    description:
      "Nghiên cứu các đối tượng và hiện tượng thiên thể bằng các dụng cụ và lý thuyết thiên văn học.",
    average_salary: 30_000_000,
    growth_rate: 0.03,
    topic_id: null,
    related_topics: null,
    skills: ["Astronomy", "Physics", "Astrophysics", "Observational Skills"],
  },
  {
    name: "Interior Designer",
    description:
      "Thiết kế không gian nội thất để nâng cao tính thẩm mỹ và chức năng.",
    average_salary: 25_000_000,
    growth_rate: 0.06,
    topic_id: null,
    related_topics: null,
    skills: [
      "Space Planning",
      "CAD Software",
      "Color Theory",
      "Interior Decoration",
    ],
  },
  {
    name: "Pilot",
    description: "Lái máy bay để vận chuyển hành khách hoặc hàng hóa.",
    average_salary: 50_000_000,
    growth_rate: 0.04,
    topic_id: null,
    related_topics: null,
    skills: [
      "Flight Training",
      "Navigation",
      "Air Traffic Control",
      "Aviation Safety",
    ],
  },
  {
    name: "Forensic Scientist",
    description:
      "Phân tích chứng cứ vật lý từ hiện trường vụ án để hỗ trợ trong các cuộc điều tra hình sự.",
    average_salary: 25_000_000,
    growth_rate: 0.06,
    topic_id: null,
    related_topics: null,
    skills: [
      "Crime Scene Investigation",
      "Lab Analysis",
      "Evidence Collection",
      "Criminal Justice",
    ],
  },
  {
    name: "Park Ranger",
    description:
      "Quản lý và bảo vệ các công viên quốc gia và khu vực giải trí.",
    average_salary: 15_000_000,
    growth_rate: 0.05,
    topic_id: null,
    related_topics: null,
    skills: [
      "Environmental Conservation",
      "Wildlife Management",
      "Public Education",
      "First Aid",
    ],
  },
  {
    name: "Fashion Designer",
    description:
      "Sáng tạo các bộ trang phục và phụ kiện, làm việc với các mẫu mã, vật liệu và phong cách.",
    average_salary: 25_000_000,
    growth_rate: 0.08,
    topic_id: null,
    related_topics: null,
    skills: ["Fashion Design", "Textile Knowledge", "Sewing", "Trend Analysis"],
  },
  {
    name: "Interpreter",
    description:
      "Dịch các từ ngữ nói hoặc ngôn ngữ ký hiệu trong thời gian thực giữa các ngôn ngữ.",
    average_salary: 20_000_000,
    growth_rate: 0.07,
    topic_id: null,
    related_topics: null,
    skills: [
      "Language Proficiency",
      "Interpretation",
      "Cultural Knowledge",
      "Communication",
    ],
  },
  {
    name: "Quality Assurance Engineer",
    description:
      "Đảm bảo chất lượng phần mềm thông qua kiểm thử tự động và thủ công.",
    average_salary: 35_000_000,
    growth_rate: 0.06,
    topic_id: null,
    related_topics: null,
    skills: ["Automation Testing", "Manual Testing", "Bug Tracking", "CI/CD"],
  },
  {
    name: "Software Developer",
    description:
      "Phát triển các ứng dụng phần mềm và giải pháp kỹ thuật cho các vấn đề kinh doanh.",
    average_salary: 40_000_000,
    growth_rate: 0.08,
    topic_id: null,
    related_topics: null,
    skills: ["JavaScript", "React", "NodeJS", "Git", "REST APIs"],
  },
  {
    name: "Cloud Engineer",
    description:
      "Xây dựng và duy trì hạ tầng đám mây, triển khai và quản lý các dịch vụ đám mây.",
    average_salary: 45_000_000,
    growth_rate: 0.09,
    topic_id: null,
    related_topics: null,
    skills: ["AWS", "Azure", "Docker", "Kubernetes", "Terraform"],
  },
  {
    name: "DevOps Engineer",
    description:
      "Đảm bảo quá trình phát triển và triển khai phần mềm diễn ra liên tục, hiệu quả và tự động.",
    average_salary: 50_000_000,
    growth_rate: 0.07,
    topic_id: null,
    related_topics: null,
    skills: ["CI/CD", "Jenkins", "Docker", "Kubernetes", "Ansible"],
  },
  {
    name: "AI Engineer",
    description:
      "Phát triển các mô hình học máy, trí tuệ nhân tạo và các giải pháp tự động hóa thông minh.",
    average_salary: 60_000_000,
    growth_rate: 0.12,
    topic_id: null,
    related_topics: null,
    skills: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Deep Learning",
      "Natural Language Processing",
    ],
  },
  {
    name: "Network Security Engineer",
    description:
      "Thiết kế, triển khai và duy trì các giải pháp bảo mật mạng để bảo vệ hệ thống và dữ liệu khỏi các mối đe dọa.",
    average_salary: 45_000_000,
    growth_rate: 0.05,
    topic_id: null,
    related_topics: null,
    skills: [
      "Firewall",
      "Network Security",
      "VPN",
      "SIEM",
      "Intrusion Detection Systems",
    ],
  },
  {
    name: "Hardware Engineer",
    description:
      "Thiết kế, phát triển và kiểm tra phần cứng cho các hệ thống máy tính và thiết bị điện tử.",
    average_salary: 40_000_000,
    growth_rate: 0.04,
    topic_id: null,
    related_topics: null,
    skills: ["Verilog", "C", "PCB Design", "FPGA", "Embedded Systems"],
  },
  {
    name: "Hardware Design Engineer",
    description:
      "Chuyên thiết kế các mô-đun phần cứng hiệu suất cao cho các hệ thống công nghệ mới.",
    average_salary: 45_000_000,
    growth_rate: 0.05,
    topic_id: null,
    related_topics: null,
    skills: ["CAD", "Hardware Design", "Circuit Design", "FPGA", "Verilog"],
  },
  {
    name: "Solutions Architect",
    description:
      "Thiết kế các giải pháp công nghệ phức tạp cho doanh nghiệp, kết hợp các hệ thống và dịch vụ đám mây.",
    average_salary: 70_000_000,
    growth_rate: 0.06,
    topic_id: null,
    related_topics: null,
    skills: [
      "System Design",
      "Cloud Computing",
      "Architectural Patterns",
      "Microservices",
      "AWS",
    ],
  },
  {
    name: "Systems Engineer",
    description:
      "Thiết kế và triển khai các hệ thống phức tạp, đảm bảo khả năng mở rộng và hiệu suất.",
    average_salary: 45_000_000,
    growth_rate: 0.05,
    topic_id: null,
    related_topics: null,
    skills: [
      "Linux",
      "VMware",
      "Automation",
      "Networking",
      "Systems Integration",
    ],
  },
  {
    name: "Database Engineer",
    description:
      "Quản lý, tối ưu hóa và bảo mật các cơ sở dữ liệu, đảm bảo hiệu suất cao cho các ứng dụng.",
    average_salary: 50_000_000,
    growth_rate: 0.04,
    topic_id: null,
    related_topics: null,
    skills: ["SQL", "PostgreSQL", "Database Optimization", "MySQL", "NoSQL"],
  },
  {
    name: "ML Engineer",
    description:
      "Xây dựng và triển khai các mô hình học máy để giải quyết các vấn đề kinh doanh phức tạp.",
    average_salary: 60_000_000,
    growth_rate: 0.11,
    topic_id: null,
    related_topics: null,
    skills: [
      "Python",
      "Machine Learning",
      "TensorFlow",
      "Keras",
      "Data Science",
    ],
  },
  {
    name: "Quality Assurance",
    description:
      "Đảm bảo chất lượng phần mềm thông qua kiểm thử tự động và thủ công.",
    average_salary: 30_000_000,
    growth_rate: 0.06,
    topic_id: null,
    related_topics: null,
    skills: [
      "Automation Testing",
      "Manual Testing",
      "Bug Tracking",
      "CI/CD",
      "Jest",
      "Cypress",
    ],
  },
  {
    name: "Software Development",
    description:
      "Phát triển các ứng dụng phần mềm và giải pháp kỹ thuật cho các vấn đề kinh doanh.",
    average_salary: 40_000_000,
    growth_rate: 0.08,
    topic_id: null,
    related_topics: null,
    skills: [
      "JavaScript",
      "TypeScript",
      "ReactJS",
      "NodeJS",
      "Git",
      "REST APIs",
      "GraphQL",
    ],
  },
  {
    name: "Cloud Computing",
    description:
      "Quản lý hạ tầng đám mây và triển khai các dịch vụ cloud cho doanh nghiệp.",
    average_salary: 45_000_000,
    growth_rate: 0.09,
    topic_id: null,
    related_topics: null,
    skills: [
      "AWS",
      "Azure",
      "Google Cloud Platform",
      "Docker",
      "Kubernetes",
      "Terraform",
    ],
  },
  {
    name: "DevOps",
    description:
      "Đảm bảo quá trình phát triển và triển khai phần mềm diễn ra liên tục, hiệu quả và tự động.",
    average_salary: 50_000_000,
    growth_rate: 0.07,
    topic_id: null,
    related_topics: null,
    skills: [
      "CI/CD",
      "Jenkins",
      "Docker",
      "Kubernetes",
      "Ansible",
      "Terraform",
    ],
  },
  {
    name: "Artificial Intelligence",
    description:
      "Phát triển các mô hình học máy, trí tuệ nhân tạo và các giải pháp tự động hóa thông minh.",
    average_salary: 60_000_000,
    growth_rate: 0.12,
    topic_id: null,
    related_topics: null,
    skills: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Deep Learning",
      "Natural Language Processing",
      "Machine Learning",
    ],
  },
  {
    name: "Network & Security",
    description:
      "Quản lý và bảo vệ hạ tầng mạng, bảo mật các hệ thống và dữ liệu khỏi các mối đe dọa.",
    average_salary: 45_000_000,
    growth_rate: 0.05,
    topic_id: null,
    related_topics: null,
    skills: [
      "Firewall",
      "Network Security",
      "VPN",
      "SIEM",
      "Intrusion Detection Systems",
      "TLS/SSL",
    ],
  },
  {
    name: "Hardware",
    description:
      "Thiết kế, phát triển và kiểm tra phần cứng cho các hệ thống máy tính và thiết bị điện tử.",
    average_salary: 45_000_000,
    growth_rate: 0.04,
    topic_id: null,
    related_topics: null,
    skills: [
      "Verilog",
      "C",
      "PCB Design",
      "FPGA",
      "Embedded Systems",
      "Hardware Design",
    ],
  },
];
