export const careerHistories = [
  {
    job_title: "Software Engineer",
    status: "active",
    prediction_date: new Date("2025-01-01"),
    salary_prediction: {
      min_salary: 5_000_000,
      max_salary: 100_000_000,
      avg_salary: 20_000_000,
      trend: "increasing",
      confidence: 0.95,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 100,
      confidence: 0.95,
      average_openings_per_posting: 10,
    },
  },
  {
    job_title: "Full Stack Developer",
    status: "active",
    prediction_date: new Date("2025-02-01"),
    salary_prediction: {
      min_salary: 15_000_000,
      max_salary: 45_000_000,
      avg_salary: 30_000_000,
      trend: "increasing",
      confidence: 0.9,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 80,
      confidence: 0.9,
      average_openings_per_posting: 8,
    },
  },
  {
    job_title: "DevOps Engineer",
    status: "active",
    prediction_date: new Date("2025-03-01"),
    salary_prediction: {
      min_salary: 20_000_000,
      max_salary: 70_000_000,
      avg_salary: 45_000_000,
      trend: "increasing",
      confidence: 0.85,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 60,
      confidence: 0.85,
      average_openings_per_posting: 6,
    },
  },
  {
    job_title: "AI Engineer",
    status: "active",
    prediction_date: new Date("2025-04-01"),
    salary_prediction: {
      min_salary: 25_000_000,
      max_salary: 80_000_000,
      avg_salary: 50_000_000,
      trend: "increasing",
      confidence: 0.95,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 40,
      confidence: 0.95,
      average_openings_per_posting: 4,
    },
  },
  {
    job_title: "Mobile App Developer",
    status: "active",
    prediction_date: new Date("2025-05-01"),
    salary_prediction: {
      min_salary: 15_000_000,
      max_salary: 45_000_000,
      avg_salary: 30_000_000,
      trend: "increasing",
      confidence: 0.9,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 70,
      confidence: 0.9,
      average_openings_per_posting: 7,
    },
  },
  {
    job_title: "QA Engineer",
    status: "active",
    prediction_date: new Date("2025-06-01"),
    salary_prediction: {
      min_salary: 12_000_000,
      max_salary: 35_000_000,
      avg_salary: 25_000_000,
      trend: "increasing",
      confidence: 0.85,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 50,
      confidence: 0.85,
      average_openings_per_posting: 5,
    },
  },
  {
    job_title: "Data Scientist",
    status: "active",
    prediction_date: new Date("2025-07-01"),
    salary_prediction: {
      min_salary: 20_000_000,
      max_salary: 65_000_000,
      avg_salary: 40_000_000,
      trend: "increasing",
      confidence: 0.95,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 45,
      confidence: 0.95,
      average_openings_per_posting: 4.5,
    },
  },
  {
    job_title: "UI/UX Designer",
    status: "active",
    prediction_date: new Date("2025-08-01"),
    salary_prediction: {
      min_salary: 15_000_000,
      max_salary: 60_000_000,
      avg_salary: 35_000_000,
      trend: "increasing",
      confidence: 0.9,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 55,
      confidence: 0.9,
      average_openings_per_posting: 5.5,
    },
  },
  {
    job_title: "Cybersecurity Analyst",
    status: "active",
    prediction_date: new Date("2025-09-01"),
    salary_prediction: {
      min_salary: 18_000_000,
      max_salary: 70_000_000,
      avg_salary: 40_000_000,
      trend: "increasing",
      confidence: 0.95,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 35,
      confidence: 0.95,
      average_openings_per_posting: 3.5,
    },
  },
  {
    job_title: "Solutions Architect",
    status: "active",
    prediction_date: new Date("2025-10-01"),
    salary_prediction: {
      min_salary: 30_000_000,
      max_salary: 90_000_000,
      avg_salary: 60_000_000,
      trend: "increasing",
      confidence: 0.9,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 25,
      confidence: 0.9,
      average_openings_per_posting: 2.5,
    },
  },
  {
    job_title: "Hardware Engineer",
    status: "active",
    prediction_date: new Date("2025-11-01"),
    salary_prediction: {
      min_salary: 20_000_000,
      max_salary: 80_000_000,
      avg_salary: 45_000_000,
      trend: "increasing",
      confidence: 0.85,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 30,
      confidence: 0.85,
      average_openings_per_posting: 3,
    },
  },
  {
    job_title: "Database Engineer",
    status: "active",
    prediction_date: new Date("2025-12-01"),
    salary_prediction: {
      min_salary: 18_000_000,
      max_salary: 65_000_000,
      avg_salary: 40_000_000,
      trend: "increasing",
      confidence: 0.9,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 40,
      confidence: 0.9,
      average_openings_per_posting: 4,
    },
  },
  {
    job_title: "ML Engineer",
    status: "active",
    prediction_date: new Date("2026-01-01"),
    salary_prediction: {
      min_salary: 25_000_000,
      max_salary: 85_000_000,
      avg_salary: 50_000_000,
      trend: "increasing",
      confidence: 0.95,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 35,
      confidence: 0.95,
      average_openings_per_posting: 3.5,
    },
  },
  {
    job_title: "Software Engineer",
    status: "active",
    prediction_date: new Date("2025-04-01"),
    salary_prediction: {
      min_salary: 15_000_000,
      max_salary: 60_000_000,
      avg_salary: 35_000_000,
      trend: "increasing",
      confidence: 0.85,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 50,
      confidence: 0.85,
      average_openings_per_posting: 4,
    },
  },
  {
    job_title: "Full Stack Developer",
    status: "active",
    prediction_date: new Date("2025-05-01"),
    salary_prediction: {
      min_salary: 20_000_000,
      max_salary: 70_000_000,
      avg_salary: 40_000_000,
      trend: "stable",
      confidence: 0.8,
    },
    job_postings_prediction: {
      trend: "stable",
      total_openings: 35,
      confidence: 0.8,
      average_openings_per_posting: 3,
    },
  },
  {
    job_title: "DevOps Engineer",
    status: "active",
    prediction_date: new Date("2025-06-01"),
    salary_prediction: {
      min_salary: 25_000_000,
      max_salary: 80_000_000,
      avg_salary: 45_000_000,
      trend: "increasing",
      confidence: 0.9,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 25,
      confidence: 0.9,
      average_openings_per_posting: 2.5,
    },
  },
  {
    job_title: "Mobile App Developer",
    status: "active",
    prediction_date: new Date("2025-07-01"),
    salary_prediction: {
      min_salary: 18_000_000,
      max_salary: 65_000_000,
      avg_salary: 38_000_000,
      trend: "decreasing",
      confidence: 0.75,
    },
    job_postings_prediction: {
      trend: "decreasing",
      total_openings: 20,
      confidence: 0.75,
      average_openings_per_posting: 2,
    },
  },
  {
    job_title: "AI Engineer",
    status: "active",
    prediction_date: new Date("2025-08-01"),
    salary_prediction: {
      min_salary: 30_000_000,
      max_salary: 90_000_000,
      avg_salary: 55_000_000,
      trend: "increasing",
      confidence: 0.95,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 30,
      confidence: 0.95,
      average_openings_per_posting: 3,
    },
  },
  {
    job_title: "UI/UX Designer",
    status: "active",
    prediction_date: new Date("2025-09-01"),
    salary_prediction: {
      min_salary: 15_000_000,
      max_salary: 55_000_000,
      avg_salary: 32_000_000,
      trend: "stable",
      confidence: 0.8,
    },
    job_postings_prediction: {
      trend: "stable",
      total_openings: 25,
      confidence: 0.8,
      average_openings_per_posting: 2.5,
    },
  },
  {
    job_title: "Data Scientist",
    status: "active",
    prediction_date: new Date("2025-10-01"),
    salary_prediction: {
      min_salary: 22_000_000,
      max_salary: 75_000_000,
      avg_salary: 45_000_000,
      trend: "increasing",
      confidence: 0.85,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 35,
      confidence: 0.85,
      average_openings_per_posting: 3.5,
    },
  },
  {
    job_title: "QA Engineer",
    status: "active",
    prediction_date: new Date("2025-11-01"),
    salary_prediction: {
      min_salary: 12_000_000,
      max_salary: 45_000_000,
      avg_salary: 28_000_000,
      trend: "stable",
      confidence: 0.75,
    },
    job_postings_prediction: {
      trend: "stable",
      total_openings: 20,
      confidence: 0.75,
      average_openings_per_posting: 2,
    },
  },
  {
    job_title: "Software Engineer",
    status: "active",
    prediction_date: new Date("2025-12-01"),
    salary_prediction: {
      min_salary: 15_000_000,
      max_salary: 100_000_000,
      avg_salary: 45_000_000,
      trend: "increasing",
      confidence: 0.9,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 50,
      confidence: 0.9,
      average_openings_per_posting: 3,
    },
  },
  {
    job_title: "Full Stack Developer",
    status: "active",
    prediction_date: new Date("2025-12-15"),
    salary_prediction: {
      min_salary: 20_000_000,
      max_salary: 80_000_000,
      avg_salary: 45_000_000,
      trend: "increasing",
      confidence: 0.85,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 40,
      confidence: 0.85,
      average_openings_per_posting: 2.5,
    },
  },
  {
    job_title: "DevOps Engineer",
    status: "active",
    prediction_date: new Date("2025-11-15"),
    salary_prediction: {
      min_salary: 25_000_000,
      max_salary: 90_000_000,
      avg_salary: 55_000_000,
      trend: "increasing",
      confidence: 0.8,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 30,
      confidence: 0.8,
      average_openings_per_posting: 2,
    },
  },
  {
    job_title: "Mobile App Developer",
    status: "active",
    prediction_date: new Date("2025-12-20"),
    salary_prediction: {
      min_salary: 18_000_000,
      max_salary: 70_000_000,
      avg_salary: 40_000_000,
      trend: "stable",
      confidence: 0.75,
    },
    job_postings_prediction: {
      trend: "stable",
      total_openings: 35,
      confidence: 0.75,
      average_openings_per_posting: 3,
    },
  },
  {
    job_title: "AI Engineer",
    status: "active",
    prediction_date: new Date("2025-11-20"),
    salary_prediction: {
      min_salary: 30_000_000,
      max_salary: 120_000_000,
      avg_salary: 65_000_000,
      trend: "increasing",
      confidence: 0.9,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 25,
      confidence: 0.9,
      average_openings_per_posting: 2.5,
    },
  },
  {
    job_title: "Data Scientist",
    status: "active",
    prediction_date: new Date("2025-12-25"),
    salary_prediction: {
      min_salary: 25_000_000,
      max_salary: 100_000_000,
      avg_salary: 55_000_000,
      trend: "increasing",
      confidence: 0.85,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 30,
      confidence: 0.85,
      average_openings_per_posting: 3,
    },
  },
  {
    job_title: "Solutions Architect",
    status: "active",
    prediction_date: new Date("2025-11-25"),
    salary_prediction: {
      min_salary: 40_000_000,
      max_salary: 150_000_000,
      avg_salary: 85_000_000,
      trend: "stable",
      confidence: 0.8,
    },
    job_postings_prediction: {
      trend: "stable",
      total_openings: 15,
      confidence: 0.8,
      average_openings_per_posting: 1.5,
    },
  },
  {
    job_title: "Hardware Engineer",
    status: "active",
    prediction_date: new Date("2025-12-30"),
    salary_prediction: {
      min_salary: 20_000_000,
      max_salary: 90_000_000,
      avg_salary: 50_000_000,
      trend: "decreasing",
      confidence: 0.7,
    },
    job_postings_prediction: {
      trend: "decreasing",
      total_openings: 20,
      confidence: 0.7,
      average_openings_per_posting: 2,
    },
  },
  {
    job_title: "Cybersecurity Analyst",
    status: "active",
    prediction_date: new Date("2025-11-30"),
    salary_prediction: {
      min_salary: 25_000_000,
      max_salary: 100_000_000,
      avg_salary: 55_000_000,
      trend: "increasing",
      confidence: 0.85,
    },
    job_postings_prediction: {
      trend: "increasing",
      total_openings: 25,
      confidence: 0.85,
      average_openings_per_posting: 2.5,
    },
  },
];
