import { careers } from "./career";

export const jobPostings = [
  {
    job_title: "Senior Frontend Developer",
    salary_min: 30_000_000,
    salary_max: 60_000_000,
    company_id: "VNG Corporation",
    job_description:
      "We are looking for a Senior Frontend Developer with expertise in React and TypeScript to join our growing team. You will be responsible for building and maintaining user interfaces for our web applications.",
    position: "Software Engineer",
    yof: "Senior",
    date_posted: new Date("2025-01-15"),
    skills: ["JavaScript", "TypeScript", "ReactJS"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Full Stack Developer",
    salary_min: 25_000_000,
    salary_max: 45_000_000,
    company_id: "Google",
    job_description:
      "Join our dynamic team as a Full Stack Developer. You'll work on both frontend and backend development, helping us build scalable and responsive web applications.",
    position: "Full Stack Developer",
    yof: "Mid-level",
    date_posted: new Date("2025-02-05"),
    skills: ["TypeScript", "ReactJS", "NodeJS", "MongoDB"],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "DevOps Engineer",
    salary_min: 35_000_000,
    salary_max: 70_000_000,
    company_id: "Shopee",
    job_description:
      "We're seeking an experienced DevOps Engineer to help us improve our CI/CD pipeline and infrastructure. You'll work with Docker, Kubernetes, and cloud platforms to ensure smooth deployments and system reliability.",
    position: "DevOps Engineer",
    yof: "Senior",
    date_posted: new Date("2025-03-20"),
    skills: ["Docker", "Kubernetes", "AWS", "CI/CD"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Junior Backend Developer",
    salary_min: 15_000_000,
    salary_max: 25_000_000,
    company_id: "W3Schools.com",
    job_description:
      "Great opportunity for a Junior Backend Developer to join our team. You'll be working with Node.js and Express to build RESTful APIs and microservices.",
    position: "Software Engineer",
    yof: "Junior",
    date_posted: new Date("2025-01-01"),
    skills: ["JavaScript", "NodeJS", "ExpressJS"],
    location: "Da Nang, Vietnam",
    number_of_openings: 4,
  },
  {
    job_title: "Machine Learning Engineer",
    salary_min: 40_000_000,
    salary_max: 80_000_000,
    company_id: "KMS Technology - Mexico",
    job_description:
      "Join our AI team as a Machine Learning Engineer. You'll be working on cutting-edge ML models to solve real-world problems in our products.",
    position: "AI Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-25"),
    skills: ["Python", "Pandas", "NumPy", "Scikit-learn"],
    location: "Mexico City, Mexico",
    number_of_openings: 2,
  },
  {
    job_title: "React Native Developer",
    salary_min: 25_000_000,
    salary_max: 45_000_000,
    company_id: "VNG Corporation",
    job_description:
      "We are looking for a React Native Developer to build and maintain cross-platform mobile applications. You should have experience with React Native and mobile app development.",
    position: "Mobile App Developer",
    yof: "Mid-level",
    date_posted: new Date("2025-03-05"),
    skills: ["JavaScript", "ReactJS", "React Native"],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "QA Engineer",
    salary_min: 20_000_000,
    salary_max: 35_000_000,
    company_id: "Google",
    job_description:
      "Join our QA team to ensure the quality of our software products. You'll be responsible for designing and implementing test cases, automated testing, and identifying bugs.",
    position: "QA Engineer",
    yof: "Mid-level",
    date_posted: new Date("2025-01-28"),
    skills: ["Jest", "Cypress", "Testing Library"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Data Engineer",
    salary_min: 35_000_000,
    salary_max: 65_000_000,
    company_id: "VNG Corporation",
    job_description:
      "We're seeking a Data Engineer to help us build and maintain our data pipelines and infrastructure. You'll work with big data technologies and ensure data quality and availability.",
    position: "Data Scientist",
    yof: "Senior",
    date_posted: new Date("2025-02-15"),
    skills: ["Python", "MongoDB", "PostgreSQL", "Redis"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Intern Frontend Developer",
    salary_min: 5_000_000,
    salary_max: 10_000_000,
    company_id: "W3Schools.com",
    job_description:
      "Great opportunity for students or recent graduates to gain real-world experience in frontend development. You'll be mentored by senior developers while working on real projects.",
    position: "Software Engineer",
    yof: "Intern",
    date_posted: new Date("2025-03-10"),
    skills: ["JavaScript", "HTML", "CSS"],
    location: "Da Nang, Vietnam",
    number_of_openings: 5,
  },
  {
    job_title: "Technical Lead",
    salary_min: 50_000_000,
    salary_max: 100_000_000,
    company_id: "KMS Technology - Mexico",
    job_description:
      "We're looking for a Technical Lead to oversee our development team and projects. You'll be responsible for technical decision-making, mentoring team members, and ensuring project success.",
    position: "Software Engineer",
    yof: "Lead",
    date_posted: new Date("2025-01-20"),
    skills: ["TypeScript", "ReactJS", "ExpressJS", "Git"],
    location: "Mexico City, Mexico",
    number_of_openings: 1,
  },
  {
    job_title: "Fresher Android Developer",
    salary_min: 8_000_000,
    salary_max: 15_000_000,
    company_id: "VNG Corporation",
    job_description:
      "Looking for a fresher Android developer to join our mobile app team. You'll be working on our Android applications and learning from experienced developers.",
    position: "Mobile App Developer",
    yof: "Fresher",
    date_posted: new Date("2025-02-15"),
    skills: ["Java", "Android", "Kotlin"],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Principal Software Architect",
    salary_min: 80_000_000,
    salary_max: 150_000_000,
    company_id: "Google",
    job_description:
      "Join our team as a Principal Software Architect to design and implement large-scale systems. You'll be responsible for making critical architectural decisions and guiding development teams.",
    position: "Software Engineer",
    yof: "Principal/Expert",
    date_posted: new Date("2025-01-10"),
    skills: ["System Design", "Microservices", "Cloud Architecture", "AWS"],
    location: "Hanoi, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Mid-level iOS Developer",
    salary_min: 25_000_000,
    salary_max: 45_000_000,
    company_id: "Shopee",
    job_description:
      "We're looking for an iOS developer with 3-5 years of experience to join our mobile development team. You'll work on our iOS applications and improve the user experience.",
    position: "Mobile App Developer",
    yof: "Mid-level",
    date_posted: new Date("2025-01-20"),
    skills: ["Swift", "Objective-C", "UIKit", "SwiftUI"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Senior UX/UI Designer",
    salary_min: 30_000_000,
    salary_max: 60_000_000,
    company_id: "W3Schools.com",
    job_description:
      "Seeking an experienced UX/UI Designer to create beautiful and functional user interfaces for our web and mobile applications.",
    position: "UI/UX Designer",
    yof: "Senior",
    date_posted: new Date("2025-02-15"),
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping"],
    location: "Da Nang, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Blockchain Developer",
    salary_min: 15_000_000,
    salary_max: 45_000_000,
    company_id: "KMS Technology - Mexico",
    job_description:
      "Join our blockchain team to develop decentralized applications and smart contracts. You should have experience with blockchain technologies and smart contract development.",
    position: "Software Engineer",
    yof: "Senior",
    date_posted: new Date("2025-01-15"),
    skills: ["Solidity", "Ethereum", "Web3.js", "Smart Contracts"],
    location: "Mexico City, Mexico",
    number_of_openings: 2,
  },
  {
    job_title: "Lead Data Scientist",
    salary_min: 40_000_000,
    salary_max: 80_000_000,
    company_id: "Google",
    job_description:
      "We're seeking a Lead Data Scientist to head our data science team. You'll be responsible for developing machine learning models and managing a team of data scientists.",
    position: "Data Scientist",
    yof: "Lead",
    date_posted: new Date("2025-02-20"),
    skills: ["Python", "Machine Learning", "Deep Learning", "TensorFlow"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Fresher Web Developer",
    salary_min: 8_000_000,
    salary_max: 12_000_000,
    company_id: "VNG Corporation",
    job_description:
      "Great opportunity for fresh graduates to start their career in web development. You'll be working on our web applications and learning modern web technologies.",
    position: "Software Engineer",
    yof: "Fresher",
    date_posted: new Date("2025-03-10"),
    skills: ["HTML", "CSS", "JavaScript", "React"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 5,
  },
  {
    job_title: "Junior Data Scientist",
    salary_min: 12_000_000,
    salary_max: 20_000_000,
    company_id: "W3Schools.com",
    job_description:
      "Looking for a Junior Data Scientist to help analyze business data and provide insights. You'll be working with our data team to create reports and dashboards.",
    position: "Data Scientist",
    yof: "Junior",
    date_posted: new Date("2025-01-25"),
    skills: ["SQL", "Excel", "Data Visualization", "Power BI"],
    location: "Da Nang, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Intern Backend Developer",
    salary_min: 5_000_000,
    salary_max: 8_000_000,
    company_id: "VNG Corporation",
    job_description:
      "Internship opportunity for students interested in backend development. You'll be working with our backend team and learning about server-side technologies.",
    position: "Software Engineer",
    yof: "Intern",
    date_posted: new Date("2025-02-15"),
    skills: ["Java", "Spring Boot", "SQL", "APIs"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 4,
  },
  {
    job_title: "Principal Cloud Architect",
    salary_min: 60_000_000,
    salary_max: 120_000_000,
    company_id: "Google",
    job_description:
      "We're looking for an experienced Cloud Architect to design and implement our cloud infrastructure. You'll be responsible for designing scalable, secure, and efficient cloud solutions.",
    position: "DevOps Engineer",
    yof: "Principal/Expert",
    date_posted: new Date("2025-03-05"),
    skills: ["AWS", "Azure", "GCP", "Infrastructure as Code"],
    location: "Hanoi, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Lead Frontend Developer",
    salary_min: 35_000_000,
    salary_max: 70_000_000,
    company_id: "Shopee",
    job_description:
      "Join our team as a Lead Frontend Developer to oversee our frontend development efforts. You'll be managing a team of frontend developers and setting technical direction.",
    position: "Software Engineer",
    yof: "Lead",
    date_posted: new Date("2025-01-20"),
    skills: ["JavaScript", "TypeScript", "React", "Vue.js"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Junior DevOps Engineer",
    salary_min: 12_000_000,
    salary_max: 20_000_000,
    company_id: "KMS Technology - Mexico",
    job_description:
      "We're seeking a Junior DevOps Engineer to support our DevOps team. You'll be learning about CI/CD pipelines, container technologies, and cloud infrastructure.",
    position: "DevOps Engineer",
    yof: "Junior",
    date_posted: new Date("2025-02-10"),
    skills: ["Docker", "Jenkins", "Linux", "Git"],
    location: "Mexico City, Mexico",
    number_of_openings: 2,
  },
  {
    job_title: "Intern Machine Learning Engineer",
    salary_min: 5_000_000,
    salary_max: 8_000_000,
    company_id: "W3Schools.com",
    job_description:
      "Internship opportunity for students interested in machine learning. You'll be working with our AI team and learning about ML algorithms and applications.",
    position: "AI Engineer",
    yof: "Intern",
    date_posted: new Date("2025-03-15"),
    skills: ["Python", "Pandas", "NumPy", "Machine Learning"],
    location: "Da Nang, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Mid-level Backend Developer",
    salary_min: 20_000_000,
    salary_max: 35_000_000,
    company_id: "VNG Corporation",
    job_description:
      "Join our backend team to build robust and scalable APIs and services. You'll be working with modern technologies to develop server-side applications.",
    position: "Software Engineer",
    yof: "Mid-level",
    date_posted: new Date("2025-01-30"),
    skills: ["NodeJS", "ExpressJS", "MongoDB", "PostgreSQL"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 4,
  },
  {
    job_title: "Java Developer",
    salary_min: 18_000_000,
    salary_max: 30_000_000,
    company_id: "FPT Software",
    job_description:
      "We're looking for a Java Developer to join our enterprise solutions team. You'll be working on developing and maintaining Java-based applications for our global clients.",
    position: "Software Engineer",
    yof: "Mid-level",
    date_posted: new Date("2025-02-25"),
    skills: ["Java", "Spring Boot", "Hibernate", "MySQL"],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Senior Software Engineer",
    salary_min: 30_000_000,
    salary_max: 60_000_000,
    company_id: "FPT Software",
    job_description:
      "Join our team as a Senior Software Engineer to design and implement complex software systems. You'll lead technical discussions and mentor junior developers.",
    position: "Software Engineer",
    yof: "Senior",
    date_posted: new Date("2025-03-01"),
    skills: ["Java", "Microservices", "Docker", "Kubernetes"],
    location: "Hanoi, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Frontend Developer",
    salary_min: 18_000_000,
    salary_max: 35_000_000,
    company_id: "Tiki Corporation",
    job_description:
      "We're seeking a Frontend Developer to help build and maintain our e-commerce platform. You'll work on creating responsive and user-friendly interfaces.",
    position: "Software Engineer",
    yof: "Mid-level",
    date_posted: new Date("2025-01-10"),
    skills: ["JavaScript", "ReactJS", "HTML", "CSS"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Backend Developer",
    salary_min: 25_000_000,
    salary_max: 50_000_000,
    company_id: "Tiki Corporation",
    job_description:
      "Join our backend team to develop and optimize our e-commerce platform's APIs and services. You'll work with high-traffic systems and focus on performance and scalability.",
    position: "Software Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-05"),
    skills: ["PHP", "Laravel", "MySQL", "Redis"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Cloud Solutions Architect",
    salary_min: 60_000_000,
    salary_max: 120_000_000,
    company_id: "Microsoft",
    job_description:
      "We're looking for a Cloud Solutions Architect to design and implement Azure-based solutions for our enterprise customers. You'll work with clients to understand their requirements and provide technical leadership.",
    position: "Cloud Solutions Architect",
    yof: "Lead",
    date_posted: new Date("2025-01-10"),
    skills: [
      "Azure",
      "Cloud Architecture",
      "Infrastructure as Code",
      "Networking",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "AI Research Scientist",
    salary_min: 80_000_000,
    salary_max: 150_000_000,
    company_id: "Microsoft",
    job_description:
      "Join our AI research team to advance the state-of-the-art in artificial intelligence. You'll work on cutting-edge research projects and publish papers in top-tier conferences.",
    position: "AI Engineer",
    yof: "Principal/Expert",
    date_posted: new Date("2025-02-05"),
    skills: [
      "Machine Learning",
      "Deep Learning",
      "Natural Language Processing",
      "Computer Vision",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Mobile App Developer",
    salary_min: 15_000_000,
    salary_max: 35_000_000,
    company_id: "Momo",
    job_description:
      "We're looking for a Mobile App Developer to join our team and help improve our mobile payment application. You'll work on features that millions of Vietnamese users rely on daily.",
    position: "Mobile App Developer",
    yof: "Mid-level",
    date_posted: new Date("2025-01-20"),
    skills: ["Android", "Kotlin", "iOS", "Swift"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 4,
  },
  {
    job_title: "Financial Software Engineer",
    salary_min: 40_000_000,
    salary_max: 80_000_000,
    company_id: "Momo",
    job_description:
      "Join our team as a Financial Software Engineer to develop secure and reliable systems for digital payments and financial transactions.",
    position: "Backend Developer",
    yof: "Senior",
    date_posted: new Date("2025-02-15"),
    skills: ["Java", "Spring", "Security", "Payment Systems"],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Product Manager",
    salary_min: 50_000_000,
    salary_max: 100_000_000,
    company_id: "Grab",
    job_description:
      "We're seeking a Product Manager to lead the development of new features for our super app. You'll work with cross-functional teams to define product requirements and drive execution.",
    position: "Product Manager",
    yof: "Lead",
    date_posted: new Date("2025-01-25"),
    skills: ["Product Strategy", "Agile", "User Research", "Data Analysis"],
    location: "Singapore",
    number_of_openings: 2,
  },
  {
    job_title: "Backend Engineer",
    salary_min: 40_000_000,
    salary_max: 80_000_000,
    company_id: "Grab",
    job_description:
      "Join our backend team to build and scale our microservices architecture. You'll work on high-volume, real-time systems that power our transportation and food delivery platform.",
    position: "Backend Developer",
    yof: "Senior",
    date_posted: new Date("2025-02-18"),
    skills: ["Go", "Microservices", "Kubernetes", "Distributed Systems"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Software Engineer",
    salary_min: 15_000_000,
    salary_max: 35_000_000,
    company_id: "CMC Global",
    job_description:
      "We're looking for a Software Engineer to join our team working on enterprise projects. You'll collaborate with global clients to deliver high-quality software solutions.",
    position: "Backend Developer",
    yof: "Mid-level",
    date_posted: new Date("2025-01-10"),
    skills: ["Java", ".NET", "SQL", "Web Services"],
    location: "Hanoi, Vietnam",
    number_of_openings: 5,
  },
  {
    job_title: "Technical Project Manager",
    salary_min: 40_000_000,
    salary_max: 80_000_000,
    company_id: "CMC Global",
    job_description:
      "Join our team as a Technical Project Manager to lead software development projects. You'll be responsible for project planning, execution, and delivery.",
    position: "Product Manager",
    yof: "Lead",
    date_posted: new Date("2025-01-20"),
    skills: ["Project Management", "Agile", "Scrum", "JIRA"],
    location: "Da Nang, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Network Engineer",
    salary_min: 30_000_000,
    salary_max: 60_000_000,
    company_id: "Viettel Group",
    job_description:
      "We're seeking a Network Engineer to design and maintain our telecommunications infrastructure. You'll work with cutting-edge networking technologies and ensure high availability.",
    position: "Network Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-05"),
    skills: ["TCP/IP", "Routing", "Switching", "Network Security"],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Cybersecurity Analyst",
    salary_min: 20_000_000,
    salary_max: 40_000_000,
    company_id: "Viettel Group",
    job_description:
      "Join our security team as a Cybersecurity Analyst to protect our networks and systems from threats. You'll monitor, detect, and respond to security incidents.",
    position: "Cybersecurity Analyst",
    yof: "Mid-level",
    date_posted: new Date("2025-01-22"),
    skills: [
      "Security Operations",
      "SIEM",
      "Threat Hunting",
      "Incident Response",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 4,
  },
  {
    job_title: "AWS Solutions Architect",
    salary_min: 60_000_000,
    salary_max: 120_000_000,
    company_id: "Amazon",
    job_description:
      "We're looking for an AWS Solutions Architect to help our customers design and implement cloud solutions. You'll provide technical guidance and best practices for cloud adoption.",
    position: "Cloud Engineer",
    yof: "Senior",
    date_posted: new Date("2025-01-30"),
    skills: [
      "AWS",
      "Cloud Migration",
      "Architecture Design",
      "Cost Optimization",
    ],
    location: "Singapore",
    number_of_openings: 2,
  },
  {
    job_title: "Senior Software Development Engineer",
    salary_min: 70_000_000,
    salary_max: 130_000_000,
    company_id: "Amazon",
    job_description:
      "Join our engineering team to build scalable and reliable services. You'll design, develop, and deploy systems that power Amazon's global operations.",
    position: "Backend Developer",
    yof: "Senior",
    date_posted: new Date("2025-02-15"),
    skills: [
      "Java",
      "Distributed Systems",
      "High Availability",
      "Performance Optimization",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: ".NET Developer",
    salary_min: 15_000_000,
    salary_max: 35_000_000,
    company_id: "NashTech",
    job_description:
      "We're seeking a .NET Developer to work on enterprise applications for our clients. You'll develop and maintain software using Microsoft technologies.",
    position: "Backend Developer",
    yof: "Mid-level",
    date_posted: new Date("2025-01-18"),
    skills: ["C#", ".NET Core", "SQL Server", "Azure"],
    location: "Hanoi, Vietnam",
    number_of_openings: 4,
  },
  {
    job_title: "QA Automation Engineer",
    salary_min: 15_000_000,
    salary_max: 35_000_000,
    company_id: "NashTech",
    job_description:
      "Join our quality assurance team to develop and maintain automated test frameworks. You'll ensure the quality of our software through comprehensive testing strategies.",
    position: "QA Engineer",
    yof: "Mid-level",
    date_posted: new Date("2025-01-25"),
    skills: ["Selenium", "TestNG", "CI/CD", "API Testing"],
    location: "Da Nang, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Senior Cloud Engineer",
    salary_min: 6_000_000,
    salary_max: 90_000_000,
    company_id: "Microsoft",
    job_description:
      "Join our cloud infrastructure team to design and implement scalable cloud solutions. You'll work with Azure and help customers migrate to the cloud.",
    position: "Cloud Engineer",
    yof: "Senior",
    date_posted: new Date("2025-01-15"),
    skills: ["Azure", "Terraform", "Kubernetes", "DevOps"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Frontend Tech Lead",
    salary_min: 7_000_000,
    salary_max: 100_000_000,
    company_id: "Grab",
    job_description:
      "Lead our frontend development team in building next-generation web applications. You'll mentor developers and drive technical decisions.",
    position: "Frontend Developer",
    yof: "Lead",
    date_posted: new Date("2025-02-20"),
    skills: ["React", "TypeScript", "Web Performance", "Team Leadership"],
    location: "Singapore",
    number_of_openings: 1,
  },
  {
    job_title: "Junior DevOps Engineer",
    salary_min: 1_500_000,
    salary_max: 25_000_000,
    company_id: "VNG Corporation",
    job_description:
      "Great opportunity for a Junior DevOps Engineer to learn and grow. You'll work with CI/CD pipelines and cloud infrastructure.",
    position: "DevOps Engineer",
    yof: "Junior",
    date_posted: new Date("2025-02-10"),
    skills: ["Docker", "Jenkins", "Linux", "Shell Scripting"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Data Engineering Lead",
    salary_min: 7_500_000,
    salary_max: 110_000_000,
    company_id: "Shopee",
    job_description:
      "Lead our data engineering team in building robust data pipelines and analytics platforms. You'll drive data strategy and mentor team members.",
    position: "Data Engineer",
    yof: "Lead",
    date_posted: new Date("2025-03-05"),
    skills: ["Python", "Spark", "Data Warehousing", "ETL"],
    location: "Singapore",
    number_of_openings: 1,
  },
  {
    job_title: "Mobile App Tech Lead",
    salary_min: 6_500_000,
    salary_max: 95_000_000,
    company_id: "Momo",
    job_description:
      "Lead our mobile development team in creating innovative financial applications. You'll guide technical decisions and ensure high-quality code.",
    position: "Mobile App Developer",
    yof: "Lead",
    date_posted: new Date("2025-03-15"),
    skills: ["Android", "iOS", "Flutter", "Mobile Architecture"],
    location: "Hanoi, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Senior Backend Developer",
    salary_min: 5_500_000,
    salary_max: 85_000_000,
    company_id: "FPT Software",
    job_description:
      "Join our backend team to build scalable microservices and APIs. You'll work with modern technologies and cloud platforms.",
    position: "Backend Developer",
    yof: "Senior",
    date_posted: new Date("2025-04-22"),
    skills: ["Java", "Spring Boot", "Microservices", "AWS"],
    location: "Da Nang, Vietnam",
    number_of_openings: 4,
  },
  {
    job_title: "UI/UX Designer",
    salary_min: 2_000_000,
    salary_max: 35_000_000,
    company_id: "Tiki Corporation",
    job_description:
      "Create beautiful and intuitive user interfaces for our e-commerce platform. You'll work closely with product and development teams.",
    position: "UI/UX Designer",
    yof: "Mid-level",
    date_posted: new Date("2025-04-30"),
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Data Scientist",
    salary_min: 4_000_000,
    salary_max: 65_000_000,
    company_id: "CMC Global",
    job_description:
      "Work on exciting data science projects and build machine learning models. You'll analyze data and provide insights to drive business decisions.",
    position: "Data Scientist",
    yof: "Mid-level",
    date_posted: new Date("2025-01-12"),
    skills: ["Python", "Machine Learning", "SQL", "Data Analysis"],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Cybersecurity Analyst",
    salary_min: 5_000_000,
    salary_max: 80_000_000,
    company_id: "Viettel Group",
    job_description:
      "Protect our infrastructure and applications from security threats. You'll implement security measures and conduct security assessments.",
    position: "Cybersecurity Analyst",
    yof: "Senior",
    date_posted: new Date("2025-02-05"),
    skills: [
      "Security",
      "Network Security",
      "Penetration Testing",
      "Compliance",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Product Owner",
    salary_min: 8_000_000,
    salary_max: 120_000_000,
    company_id: "KMS Technology - Mexico",
    job_description:
      "Lead product development teams and manage product backlogs. You'll work with stakeholders to define requirements and prioritize features.",
    position: "Product Manager",
    yof: "Mid-level",
    date_posted: new Date("2025-02-18"),
    skills: ["Agile", "Scrum", "Product Strategy", "Stakeholder Management"],
    location: "Mexico City, Mexico",
    number_of_openings: 1,
  },
  {
    job_title: "QA Team Lead",
    salary_min: 10_000_000,
    salary_max: 150_000_000,
    company_id: "NashTech",
    job_description:
      "Lead our QA team in ensuring software quality. You'll develop testing strategies and mentor QA engineers.",
    position: "Quality Assurance",
    yof: "Lead",
    date_posted: new Date("2025-01-25"),
    skills: [
      "Test Planning",
      "Automation",
      "Team Leadership",
      "Quality Assurance",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Blockchain Developer",
    salary_min: 12_000_000,
    salary_max: 180_000_000,
    company_id: "W3Schools.com",
    job_description:
      "Develop blockchain solutions and smart contracts. You'll work with cutting-edge blockchain technologies.",
    position: "Software Development",
    yof: "Senior",
    date_posted: new Date("2025-02-15"),
    skills: ["Solidity", "Web3.js", "Smart Contracts", "Blockchain"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Cloud Architect",
    salary_min: 15_000_000,
    salary_max: 200_000_000,
    company_id: "Amazon",
    job_description:
      "Design and implement cloud architecture solutions. You'll help customers optimize their cloud infrastructure.",
    position: "Cloud Computing",
    yof: "Senior",
    date_posted: new Date("2025-03-28"),
    skills: ["AWS", "Cloud Architecture", "Infrastructure as Code", "DevOps"],
    location: "Singapore",
    number_of_openings: 1,
  },
  {
    job_title: "Frontend Developer",
    salary_min: 5_000_000,
    salary_max: 80_000_000,
    company_id: "Oracle",
    job_description:
      "Build modern web applications using React and TypeScript. You'll work on user interfaces for enterprise solutions.",
    position: "Software Development",
    yof: "Mid-level",
    date_posted: new Date("2025-04-10"),
    skills: ["React", "TypeScript", "CSS", "Web Development"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "DevOps Lead",
    salary_min: 13_000_000,
    salary_max: 190_000_000,
    company_id: "Salesforce",
    job_description:
      "Lead our DevOps initiatives and improve deployment processes. You'll drive automation and infrastructure improvements.",
    position: "DevOps",
    yof: "Lead",
    date_posted: new Date("2025-01-22"),
    skills: [
      "CI/CD",
      "Kubernetes",
      "Infrastructure as Code",
      "Team Leadership",
    ],
    location: "Singapore",
    number_of_openings: 1,
  },
  {
    job_title: "AI Research Engineer",
    salary_min: 12_000_000,
    salary_max: 180_000_000,
    company_id: "IBM",
    job_description:
      "Research and develop AI solutions. You'll work on cutting-edge machine learning projects.",
    position: "Artificial Intelligence",
    yof: "Senior",
    date_posted: new Date("2025-01-15"),
    skills: ["Machine Learning", "Deep Learning", "Python", "Research"],
    location: "Hanoi, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Network Cybersecurity Analyst",
    salary_min: 10_000_000,
    salary_max: 150_000_000,
    company_id: "Cisco",
    job_description:
      "Design and implement network security solutions. You'll protect enterprise networks from threats.",
    position: "Network & Security",
    yof: "Senior",
    date_posted: new Date("2025-01-20"),
    skills: ["Network Security", "Firewalls", "VPN", "Security Protocols"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Full Stack Developer",
    salary_min: 6_000_000,
    salary_max: 90_000_000,
    company_id: "Adobe",
    job_description:
      "Develop full-stack applications using modern technologies. You'll work on creative tools and solutions.",
    position: "Software Development",
    yof: "Mid-level",
    date_posted: new Date("2025-01-05"),
    skills: ["JavaScript", "Node.js", "React", "MongoDB"],
    location: "Hanoi, Vietnam",
    number_of_openings: 4,
  },
  {
    job_title: "Senior Software Engineer",
    salary_min: 12_000_000,
    salary_max: 180_000_000,
    company_id: "Qualcomm",
    job_description:
      "Join our team to develop cutting-edge semiconductor solutions. You'll work on advanced technologies and drive innovation.",
    position: "Software Development",
    yof: "Senior",
    date_posted: new Date("2025-01-10"),
    skills: ["C++", "Embedded Systems", "RTOS", "Hardware Integration"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Cloud Infrastructure Engineer",
    salary_min: 8_000_000,
    salary_max: 120_000_000,
    company_id: "Dell Technologies",
    job_description:
      "Design and implement cloud infrastructure solutions. You'll work with enterprise clients to optimize their cloud environments.",
    position: "DevOps",
    yof: "Mid-level",
    date_posted: new Date("2025-01-18"),
    skills: ["AWS", "Azure", "Terraform", "Kubernetes"],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Hardware Engineer",
    salary_min: 10_000_000,
    salary_max: 150_000_000,
    company_id: "HP Inc.",
    job_description:
      "Develop next-generation hardware solutions. You'll work on innovative products and improve performance.",
    position: "Hardware",
    yof: "Senior",
    date_posted: new Date("2025-01-08"),
    skills: ["PCB Design", "Hardware Testing", "CAD", "System Architecture"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "GPU Software Engineer",
    salary_min: 12_000_000,
    salary_max: 180_000_000,
    company_id: "NVIDIA",
    job_description:
      "Work on GPU software development and optimization. You'll help advance graphics and computing technologies.",
    position: "Software Development",
    yof: "Senior",
    date_posted: new Date("2025-01-12"),
    skills: ["CUDA", "OpenGL", "C++", "GPU Programming"],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Systems Architect",
    salary_min: 15_000_000,
    salary_max: 200_000_000,
    company_id: "Qualcomm",
    job_description:
      "Design complex system architectures for mobile and IoT devices. You'll lead technical decisions and mentor teams.",
    position: "Software Development",
    yof: "Lead",
    date_posted: new Date("2025-01-25"),
    skills: [
      "System Design",
      "Architecture",
      "Performance Optimization",
      "Team Leadership",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Storage Solutions Engineer",
    salary_min: 10_000_000,
    salary_max: 150_000_000,
    company_id: "Dell Technologies",
    job_description:
      "Develop enterprise storage solutions. You'll work on data protection and storage optimization.",
    position: "Hardware",
    yof: "Senior",
    date_posted: new Date("2025-01-28"),
    skills: [
      "Storage Systems",
      "RAID",
      "Data Protection",
      "Performance Tuning",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Printer Systems Engineer",
    salary_min: 15_000_000,
    salary_max: 30_000_000,
    company_id: "HP Inc.",
    job_description:
      "Work on printer firmware and software development. You'll improve print quality and system reliability.",
    position: "Software Development",
    yof: "Mid-level",
    date_posted: new Date("2025-01-30"),
    skills: ["Firmware", "C++", "Embedded Systems", "Print Technologies"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "AI Hardware Engineer",
    salary_min: 40_000_000,
    salary_max: 80_000_000,
    company_id: "NVIDIA",
    job_description:
      "Design AI acceleration hardware. You'll work on next-generation AI computing solutions.",
    position: "Hardware",
    yof: "Senior",
    date_posted: new Date("2025-01-31"),
    skills: [
      "AI Hardware",
      "VLSI",
      "Computer Architecture",
      "Performance Analysis",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Mobile Software Engineer",
    salary_min: 35_000_000,
    salary_max: 70_000_000,
    company_id: "Qualcomm",
    job_description:
      "Develop mobile platform software. You'll optimize performance and power efficiency.",
    position: "Software Development",
    yof: "Senior",
    date_posted: new Date("2025-01-14"),
    skills: [
      "Android",
      "Linux Kernel",
      "Mobile Development",
      "Performance Optimization",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Enterprise Solutions Architect",
    salary_min: 45_000_000,
    salary_max: 90_000_000,
    company_id: "Dell Technologies",
    job_description:
      "Design enterprise IT solutions. You'll help clients modernize their infrastructure.",
    position: "Cloud Computing",
    yof: "Senior",
    date_posted: new Date("2025-01-16"),
    skills: [
      "Enterprise Architecture",
      "Cloud Migration",
      "IT Infrastructure",
      "Consulting",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Security Researcher",
    salary_min: 40_000_000,
    salary_max: 75_000_000,
    company_id: "HP Inc.",
    job_description:
      "Research and develop security solutions. You'll protect systems from emerging threats.",
    position: "Cybersecurity Analyst",
    yof: "Senior",
    date_posted: new Date("2025-01-24"),
    skills: [
      "Security Research",
      "Threat Analysis",
      "Penetration Testing",
      "Security Protocols",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Graphics Software Engineer",
    salary_min: 40_000_000,
    salary_max: 80_000_000,
    company_id: "NVIDIA",
    job_description:
      "Develop graphics drivers and software. You'll advance gaming and professional graphics.",
    position: "Software Engineer",
    yof: "Senior",
    date_posted: new Date("2025-01-26"),
    skills: ["Graphics Programming", "DirectX", "OpenGL", "Driver Development"],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "IoT Solutions Engineer",
    salary_min: 20_000_000,
    salary_max: 40_000_000,
    company_id: "Qualcomm",
    job_description:
      "Design IoT solutions and connectivity. You'll work on smart device technologies.",
    position: "Software Engineer",
    yof: "Mid-level",
    date_posted: new Date("2025-01-05"),
    skills: ["IoT", "Wireless Protocols", "Embedded Systems", "Connectivity"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Data Center Architect",
    salary_min: 45_000_000,
    salary_max: 90_000_000,
    company_id: "Dell Technologies",
    job_description:
      "Design modern data center solutions. You'll optimize infrastructure and efficiency.",
    position: "Cloud Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-10"),
    skills: [
      "Data Center Design",
      "Infrastructure",
      "Energy Efficiency",
      "Cloud Computing",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Print Systems Developer",
    salary_min: 15_000_000,
    salary_max: 30_000_000,
    company_id: "HP Inc.",
    job_description:
      "Develop print management systems. You'll improve print workflows and security.",
    position: "Software Engineer",
    yof: "Mid-level",
    date_posted: new Date("2025-03-15"),
    skills: [
      "Print Systems",
      "Security",
      "Workflow Automation",
      "Enterprise Software",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Deep Learning Engineer",
    salary_min: 45_000_000,
    salary_max: 90_000_000,
    company_id: "NVIDIA",
    job_description:
      "Develop deep learning frameworks and tools. You'll advance AI capabilities.",
    position: "AI Engineer",
    yof: "Senior",
    date_posted: new Date("2025-04-20"),
    skills: ["Deep Learning", "PyTorch", "TensorFlow", "GPU Computing"],
    location: "Hanoi, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Wireless Systems Engineer",
    salary_min: 40_000_000,
    salary_max: 75_000_000,
    company_id: "Qualcomm",
    job_description:
      "Design wireless communication systems. You'll advance mobile connectivity.",
    position: "Hardware Engineer",
    yof: "Senior",
    date_posted: new Date("2025-01-15"),
    skills: ["Wireless Systems", "RF Design", "Signal Processing", "Protocols"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Cloud Solutions Engineer",
    salary_min: 40_000_000,
    salary_max: 80_000_000,
    company_id: "Dell Technologies",
    job_description:
      "Implement cloud solutions for enterprises. You'll optimize cloud performance.",
    position: "Cloud Engineer",
    yof: "Senior",
    date_posted: new Date("2025-01-20"),
    skills: [
      "Cloud Computing",
      "DevOps",
      "Infrastructure as Code",
      "Automation",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Security Solutions Architect",
    salary_min: 45_000_000,
    salary_max: 85_000_000,
    company_id: "HP Inc.",
    job_description:
      "Design security architectures. You'll protect enterprise systems.",
    position: "Cybersecurity Analyst",
    yof: "Senior",
    date_posted: new Date("2025-01-25"),
    skills: [
      "Cloud Computing",
      "DevOps",
      "Infrastructure as Code",
      "Automation",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "GPU Architecture Engineer",
    salary_min: 45_000_000,
    salary_max: 90_000_000,
    company_id: "NVIDIA",
    job_description:
      "Design next-generation GPU architectures. You'll push graphics technology forward.",
    position: "Hardware Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-01"),
    skills: [
      "GPU Design",
      "Computer Architecture",
      "VLSI",
      "Performance Optimization",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Cloud Infrastructure Engineer",
    salary_min: 40_000_000,
    salary_max: 80_000_000,
    company_id: "Oracle",
    job_description:
      "Build and maintain cloud infrastructure. You'll ensure high availability and scalability.",
    position: "Cloud Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-05"),
    skills: ["Cloud Computing", "Kubernetes", "Terraform", "CI/CD"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "AI Research Scientist",
    salary_min: 8_000_000,
    salary_max: 120_000_000,
    company_id: "Salesforce",
    job_description:
      "Research and develop AI solutions. You'll advance machine learning capabilities.",
    position: "AI Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-10"),
    skills: ["Machine Learning", "Deep Learning", "NLP", "Research"],
    location: "Hanoi, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Quantum Computing Researcher",
    salary_min: 9_000_000,
    salary_max: 130_000_000,
    company_id: "IBM",
    job_description:
      "Research quantum computing applications. You'll pioneer quantum technology.",
    position: "AI Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-15"),
    skills: ["Quantum Computing", "Physics", "Algorithm Design", "Research"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Network Cybersecurity Analyst",
    salary_min: 7_500_000,
    salary_max: 110_000_000,
    company_id: "Cisco",
    job_description:
      "Secure network infrastructure. You'll protect against cyber threats.",
    position: "Cybersecurity Analyst",
    yof: "Senior",
    date_posted: new Date("2025-02-20"),
    skills: ["Network Security", "Firewalls", "VPN", "Security Protocols"],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Mobile Chip Designer",
    salary_min: 8_500_000,
    salary_max: 125_000_000,
    company_id: "Qualcomm",
    job_description:
      "Design mobile processors. You'll optimize mobile performance.",
    position: "Hardware Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-25"),
    skills: [
      "Chip Design",
      "VLSI",
      "Power Optimization",
      "Mobile Architecture",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Enterprise Solutions Architect",
    salary_min: 9_000_000,
    salary_max: 135_000_000,
    company_id: "Dell Technologies",
    job_description:
      "Design enterprise IT solutions. You'll transform business infrastructure.",
    position: "Solutions Architect",
    yof: "Senior",
    date_posted: new Date("2025-03-01"),
    skills: [
      "Enterprise Architecture",
      "Cloud Computing",
      "Storage Solutions",
      "Networking",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Printer Systems Engineer",
    salary_min: 6_500_000,
    salary_max: 95_000_000,
    company_id: "HP Inc.",
    job_description:
      "Develop printer systems. You'll innovate printing technology.",
    position: "Systems Engineer",
    yof: "Senior",
    date_posted: new Date("2025-03-05"),
    skills: [
      "Embedded Systems",
      "Hardware Design",
      "Firmware",
      "Printing Technology",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Graphics Software Engineer",
    salary_min: 7_500_000,
    salary_max: 110_000_000,
    company_id: "NVIDIA",
    job_description:
      "Develop graphics drivers. You'll enhance visual computing.",
    position: "Software Engineer",
    yof: "Senior",
    date_posted: new Date("2025-03-10"),
    skills: ["Graphics Programming", "CUDA", "OpenGL", "Driver Development"],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Database Administrator",
    salary_min: 7_000_000,
    salary_max: 105_000_000,
    company_id: "Oracle",
    job_description:
      "Manage database systems. You'll ensure data integrity and performance.",
    position: "Database Engineer",
    yof: "Senior",
    date_posted: new Date("2025-03-15"),
    skills: [
      "Database Management",
      "SQL",
      "Performance Tuning",
      "Backup/Recovery",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "AI Platform Engineer",
    salary_min: 8_500_000,
    salary_max: 125_000_000,
    company_id: "Salesforce",
    job_description:
      "Build AI platforms. You'll enable machine learning at scale.",
    position: "AI Engineer",
    yof: "Senior",
    date_posted: new Date("2025-03-20"),
    skills: [
      "AI Infrastructure",
      "Distributed Systems",
      "MLOps",
      "Cloud Computing",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Quantum Software Engineer",
    salary_min: 9_000_000,
    salary_max: 130_000_000,
    company_id: "IBM",
    job_description:
      "Develop quantum software. You'll create quantum applications.",
    position: "Software Engineer",
    yof: "Senior",
    date_posted: new Date("2025-03-25"),
    skills: ["Quantum Computing", "Python", "Qiskit", "Algorithm Design"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Network Architect",
    salary_min: 8_000_000,
    salary_max: 120_000_000,
    company_id: "Cisco",
    job_description:
      "Design network architectures. You'll build scalable networks.",
    position: "Network Engineer",
    yof: "Senior",
    date_posted: new Date("2025-03-30"),
    skills: ["Network Design", "Routing", "Switching", "Network Security"],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "RF Engineer",
    salary_min: 7_500_000,
    salary_max: 110_000_000,
    company_id: "Qualcomm",
    job_description: "Design RF systems. You'll advance wireless technology.",
    position: "Hardware Engineer",
    yof: "Senior",
    date_posted: new Date("2025-01-15"),
    skills: [
      "RF Design",
      "Wireless Systems",
      "Signal Processing",
      "Antenna Design",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "Storage Solutions Architect",
    salary_min: 8_500_000,
    salary_max: 125_000_000,
    company_id: "Dell Technologies",
    job_description: "Design storage solutions. You'll optimize data storage.",
    position: "Solutions Architect",
    yof: "Senior",
    date_posted: new Date("2025-02-20"),
    skills: [
      "Storage Architecture",
      "Data Protection",
      "Performance Optimization",
      "Cloud Storage",
    ],
    location: "Da Nang, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Security Researcher",
    salary_min: 8_000_000,
    salary_max: 120_000_000,
    company_id: "HP Inc.",
    job_description:
      "Research security threats. You'll protect against vulnerabilities.",
    position: "Cybersecurity Analyst",
    yof: "Senior",
    date_posted: new Date("2025-03-10"),
    skills: [
      "Security Research",
      "Vulnerability Assessment",
      "Penetration Testing",
      "Security Tools",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "AI Hardware Engineer",
    salary_min: 9_000_000,
    salary_max: 130_000_000,
    company_id: "NVIDIA",
    job_description: "Design AI hardware. You'll accelerate machine learning.",
    position: "Hardware Engineer",
    yof: "Senior",
    date_posted: new Date("2025-04-05"),
    skills: [
      "AI Hardware",
      "Computer Architecture",
      "VLSI",
      "Performance Optimization",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Cloud Cybersecurity Analyst",
    salary_min: 8_000_000,
    salary_max: 120_000_000,
    company_id: "Oracle",
    job_description:
      "Secure cloud infrastructure. You'll protect cloud services.",
    position: "Cybersecurity Analyst",
    yof: "Senior",
    date_posted: new Date("2025-02-12"),
    skills: [
      "Cloud Security",
      "Identity Management",
      "Encryption",
      "Security Compliance",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 3,
  },
  {
    job_title: "ML Infrastructure Engineer",
    salary_min: 5_500_000,
    salary_max: 80_000_000,
    company_id: "Salesforce",
    job_description:
      "Build ML infrastructure. You'll scale machine learning systems.",
    position: "ML Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-18"),
    skills: [
      "ML Infrastructure",
      "Distributed Systems",
      "MLOps",
      "Cloud Computing",
    ],
    location: "Hanoi, Vietnam",
    number_of_openings: 2,
  },
  {
    job_title: "Quantum Hardware Engineer",
    salary_min: 6_000_000,
    salary_max: 85_000_000,
    company_id: "IBM",
    job_description:
      "Design quantum hardware. You'll advance quantum computing.",
    position: "Hardware Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-22"),
    skills: [
      "ML Infrastructure",
      "Distributed Systems",
      "MLOps",
      "Cloud Computing",
    ],
    location: "Ho Chi Minh City, Vietnam",
    number_of_openings: 1,
  },
  {
    job_title: "Cloud Cybersecurity Analyst",
    salary_min: 5_000_000,
    salary_max: 75_000_000,
    company_id: "Oracle",
    job_description:
      "Secure cloud infrastructure. You'll protect cloud services.",
    position: "Cybersecurity Analyst",
    yof: "Senior",
    date_posted: new Date("2025-02-30"),
    skills: [
      "Cloud Security",
      "Identity Management",
      "Encryption",
      "Security Compliance",
    ],
    location: "Singapore",
    number_of_openings: 2,
  },
  {
    job_title: "ML Infrastructure Engineer",
    salary_min: 5_500_000,
    salary_max: 80_000_000,
    company_id: "Salesforce",
    job_description:
      "Build ML infrastructure. You'll scale machine learning systems.",
    position: "AI Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-15"),
    skills: [
      "ML Infrastructure",
      "Distributed Systems",
      "MLOps",
      "Cloud Computing",
    ],
    location: "Tokyo, Japan",
    number_of_openings: 1,
  },
  {
    job_title: "Quantum Hardware Engineer",
    salary_min: 6_000_000,
    salary_max: 85_000_000,
    company_id: "IBM",
    job_description:
      "Design quantum hardware. You'll advance quantum computing.",
    position: "Robotics Engineer",
    yof: "Senior",
    date_posted: new Date("2025-02-20"),
    skills: [
      "ML Infrastructure",
      "Distributed Systems",
      "MLOps",
      "Cloud Computing",
    ],
    location: "Seoul, South Korea",
    number_of_openings: 2,
  },
];

const d = jobPostings
  .filter((j) => careers.every((c) => c.name !== j.position))
  .map((c) => c.position);

console.log(new Set(d));
