import { ISkill } from "src/models/skill.model";

export const skills: Partial<ISkill> & Pick<ISkill, "name">[] = [
  { name: "JavaScript" },
  { name: "TypeScript" },
  { name: "Python" },
  { name: "Java" },
  { name: "C#" },
  { name: "C++" },
  { name: "Go" },
  { name: "Rust" },
  { name: "PHP" },
  { name: "Ruby" },
  { name: "Kotlin" },
  { name: "Swift" },
  { name: "Shell Script" },
  { name: "Perl" },
  { name: "R" },
  { name: "HTML" },
  { name: "CSS" },
  { name: "Sass" },
  { name: "Tailwind CSS" },
  { name: "React" },
  { name: "NextJS" },
  { name: "VueJS" },
  { name: "NuxtJS" },
  { name: "Angular" },
  { name: "Bootstrap" },
  { name: "Adobe XD" },
  { name: "Nghiên cứu người dùng" },
  { name: "Prototyping" },
  { name: "Framer Motion" },
  { name: "Three.js" },
  { name: "Zustand" },
  { name: "Storybook" },
  { name: "NodeJS" },
  { name: "ExpressJS" },
  { name: "NestJS" },
  { name: "Django" },
  { name: "Flask" },
  { name: "Spring Boot" },
  { name: "Laravel" },
  { name: "Ruby on Rails" },
  { name: "GraphQL" },
  { name: "Apollo Server" },
  { name: "Prisma" },
  { name: "tRPC" },
  { name: "MongoDB" },
  { name: "PostgreSQL" },
  { name: "MySQL" },
  { name: "SQLite" },
  { name: "Redis" },
  { name: "Firebase" },
  { name: "ElasticSearch" },
  { name: "Neo4j" },
  { name: "SQL" },
  { name: "Oracle" },
  { name: "Docker" },
  { name: "Kubernetes" },
  { name: "AWS" },
  { name: "Azure" },
  { name: "Google Cloud Platform" },
  { name: "GCP" },
  { name: "Nginx" },
  { name: "CI/CD" },
  { name: "Terraform" },
  { name: "Ansible" },
  { name: "Prometheus" },
  { name: "Grafana" },
  { name: "Git" },
  { name: "GitHub" },
  { name: "Jira" },
  { name: "Figma" },
  { name: "Postman" },
  { name: "Linux" },
  { name: "VSCode" },
  { name: "Notion" },
  { name: "Slack" },
  { name: "ClickUp" },
  { name: "Confluence" },
  { name: "Chrome DevTools" },
  { name: "Zotero" },
  { name: "Pandas" },
  { name: "NumPy" },
  { name: "Scikit-learn" },
  { name: "TensorFlow" },
  { name: "PyTorch" },
  { name: "Matplotlib" },
  { name: "Power BI" },
  { name: "Học máy" },
  { name: "Machine Learning" },
  { name: "Deep Learning" },
  { name: "Neural Networks" },
  { name: "Jupyter Notebook" },
  { name: "OpenCV" },
  { name: "LangChain" },
  { name: "Hugging Face Transformers" },
  { name: "JWT" },
  { name: "OAuth2" },
  { name: "SSL/TLS" },
  { name: "Bảo mật mạng" },
  { name: "Tường lửa" },
  { name: "SIEM" },
  { name: "Hack đạo đức" },
  { name: "Burp Suite" },
  { name: "Metasploit" },
  { name: "Wireshark" },
  { name: "Cloud Security" },
  { name: "React Native" },
  { name: "Flutter" },
  { name: "SwiftUI" },
  { name: "Android Studio" },
  { name: "Xcode" },
  { name: "Jest" },
  { name: "Cypress" },
  { name: "Mocha" },
  { name: "Playwright" },
  { name: "TestCafe" },
  { name: "Testing Library" },
  { name: "K6" },
  { name: "Helpdesk" },
  { name: "Khắc phục sự cố" },
  { name: "Hỗ trợ khách hàng" },
  { name: "Mạng" },
  { name: "Unity" },
  { name: "Unreal Engine" },
  { name: "Mô hình 3D" },
  { name: "Markdown" },
  { name: "Tài liệu API" },
  { name: "Viết" },
  { name: "Chú ý đến chi tiết" },
  { name: "VPN" },
  { name: "Cisco" },
  { name: "TCP/IP" },
  { name: "Routing" },
  { name: "Switching" },
  { name: "SEO" },
  { name: "Google Analytics" },
  { name: "Mạng xã hội" },
  { name: "Tiếp thị qua email" },
  { name: "Keyword Research" },
  { name: "Content Strategy" },
  { name: "Social Media" },
  { name: "Market Research" },
  { name: "Advertising" },
  { name: "Campaign Management" },
  { name: "Analytics" },
  { name: "ROS" },
  { name: "Cảm biến" },
  { name: "Hệ thống điều khiển" },
  { name: "Xử lý ảnh" },
  { name: "Thiết kế hệ thống" },
  { name: "Điện toán đám mây" },
  { name: "Tự động hóa" },
  { name: "Contract Law" },
  { name: "Legal Research" },
  { name: "Compliance" },
  { name: "Negotiation" },
  { name: "Recruitment" },
  { name: "Employee Relations" },
  { name: "Performance Management" },
  { name: "HR Strategy" },
  { name: "Financial Modeling" },
  { name: "Excel" },
  { name: "Financial Analysis" },
  { name: "Investment Strategy" },
  { name: "Logistics" },
  { name: "Supply Chain" },
  { name: "Operations Strategy" },
  { name: "Accounting" },
  { name: "Taxation" },
  { name: "Audit" },
  { name: "Financial Reporting" },
  { name: "Therapy" },
  { name: "Cognitive Behavioral Therapy" },
  { name: "Psychological Assessment" },
  { name: "Mental Health" },
  { name: "Counseling" },
  { name: "Social Services" },
  { name: "Crisis Management" },
  { name: "Advocacy" },
  { name: "Animal Care" },
  { name: "Surgery" },
  { name: "Veterinary Medicine" },
  { name: "Diagnostics" },
  { name: "Nutrition" },
  { name: "Health Education" },
  { name: "Diet Plans" },
  { name: "Medical Nutrition Therapy" },
  { name: "Speech Therapy" },
  { name: "Language Development" },
  { name: "Swallowing Therapy" },
  { name: "Biomedical Devices" },
  { name: "Medical Imaging" },
  { name: "Bioinformatics" },
  { name: "CAD" },
  { name: "Agricultural Systems" },
  { name: "Sustainability" },
  { name: "Engineering Design" },
  { name: "Soil Science" },
  { name: "Marine Ecology" },
  { name: "Field Research" },
  { name: "Oceanography" },
  { name: "Biology" },
  { name: "Climate Modeling" },
  { name: "Data Analysis" },
  { name: "Meteorological Equipment" },
  { name: "Statistics" },
  { name: "Event Coordination" },
  { name: "Vendor Management" },
  { name: "Project Management" },
  { name: "Communication" },
  { name: "Real Estate Law" },
  { name: "Property Management" },
  { name: "Sales" },
  { name: "Chiropractic Care" },
  { name: "Musculoskeletal Assessment" },
  { name: "Patient Care" },
  { name: "Spinal Manipulation" },
  { name: "Film Production" },
  { name: "Directing" },
  { name: "Scriptwriting" },
  { name: "Cinematography" },
  { name: "Art History" },
  { name: "Museum Management" },
  { name: "Exhibit Planning" },
  { name: "Curation" },
  { name: "Astronomy" },
  { name: "Physics" },
  { name: "Astrophysics" },
  { name: "Observational Skills" },
  { name: "Space Planning" },
  { name: "CAD Software" },
  { name: "Color Theory" },
  { name: "Interior Decoration" },
  { name: "Flight Training" },
  { name: "Navigation" },
  { name: "Air Traffic Control" },
  { name: "Aviation Safety" },
  { name: "Crime Scene Investigation" },
  { name: "Lab Analysis" },
  { name: "Evidence Collection" },
  { name: "Criminal Justice" },
  { name: "Environmental Conservation" },
  { name: "Wildlife Management" },
  { name: "Public Education" },
  { name: "First Aid" },
  { name: "Fashion Design" },
  { name: "Textile Knowledge" },
  { name: "Sewing" },
  { name: "Trend Analysis" },
  { name: "Language Proficiency" },
  { name: "Interpretation" },
  { name: "Cultural Knowledge" },
];
