export const regionMap: { [key: string]: string[] } = {
  north: [
    "hanoi",
    "hai phong",
    "quang ninh",
    "bac ninh",
    "bac giang",
    "lang son",
    "cao bang",
    "ha giang",
    "lao cai",
    "yen bai",
    "tuyen quang",
    "thai nguyen",
    "phu tho",
    "vinh phuc",
    "bac kan",
    "ha nam",
    "nam dinh",
    "thai binh",
    "ninh binh",
    "hoa binh",
    "son la",
    "dien bien",
    "lai chau",
  ],
  central: [
    "da nang",
    "hue",
    "quang binh",
    "quang tri",
    "thua thien hue",
    "quang nam",
    "quang ngai",
    "binh dinh",
    "phu yen",
    "khanh hoa",
    "ninh thuan",
    "binh thuan",
    "kon tum",
    "gia lai",
    "dak lak",
    "dak nong",
    "lam dong",
  ],
  south: [
    "ho chi minh city",
    "binh duong",
    "dong nai",
    "ba ria - vung tau",
    "tay ninh",
    "binh phuoc",
    "long an",
    "tien giang",
    "ben tre",
    "tra vinh",
    "vinh long",
    "dong thap",
    "an giang",
    "kien giang",
    "can tho",
    "hau giang",
    "soc trang",
    "bac lieu",
    "ca mau",
  ],
};
